#!/usr/bin/env ruby 

$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), '/' ))
$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), 'lib' ))

require 'options'
require 'application'

options = Options.new
options.run

app = Application.new(options[:directory], options[:port])

puts "the beast is now serving up [#{options[:directory]}] on port #{options[:port]}, nice and hot for you." 
app.run